import type { FormConfig } from '@/lib/types';

const nutriPathBrandContent: FormConfig = {
  id: 'nutripath-brand-content',
  slug: 'nutripath-brand-content',
  title: 'NutriPath · Brand & Content Kit',
  heroAccent: 'kit',
  eyebrow: 'Client Onboarding · Brand & Content Kit · Form 2 of 2',
  description: "Share your logo, colours, the look-and-feel you love, your voice, and the words & images for your pages. Fill what you have, skip what you don't — we'll fill the gaps together.",
  client: 'NutriPath',
  sections: [
    {
      id: 'basics',
      num: '01',
      title: 'Brand basics',
      description: "The essentials we'll reference everywhere — name, tagline, and who to contact.",
      fields: [
        {
          id: 'business_name',
          type: 'text',
          label: 'Business name',
          placeholder: 'NutriPath Canada',
          required: true,
        },
        {
          id: 'tagline',
          type: 'text',
          label: 'Tagline / one-liner',
          hint: "How you'd describe NutriPath in a sentence",
          placeholder: 'CDRE & KCAT prep built by Canadian dietitians',
        },
        {
          id: 'contact_name',
          type: 'text',
          label: 'Primary contact name',
          placeholder: 'Berin Arikan, RD',
          halfWidth: true,
        },
        {
          id: 'contact_email',
          type: 'email',
          label: 'Contact email',
          placeholder: 'you@nutripath.ca',
          halfWidth: true,
        },
        {
          id: 'domain',
          type: 'text',
          label: 'Primary domain',
          placeholder: 'nutripath.ca',
        },
        {
          id: 'has_brand_guidelines',
          type: 'select',
          label: 'Do you have existing brand guidelines?',
          options: [
            { value: 'full', label: "Yes — full brand guide (I'll upload it)" },
            { value: 'partial', label: 'Partial — logo & colours only' },
            { value: 'none', label: 'No — branding is part of scope' },
          ],
        },
        {
          id: 'desired_feeling',
          type: 'textarea',
          label: 'In one or two sentences, what should every visitor feel when they land on the site?',
          placeholder: 'e.g., Calm and reassured — like a knowledgeable dietitian has their back and they\'re finally in the right place.',
          rows: 3,
        },
      ],
    },

    {
      id: 'logo',
      num: '02',
      title: 'Logo & brand files',
      description: 'Upload what you have. Vector (SVG / AI / PDF) is best, but PNG is fine.',
      fields: [
        {
          id: 'primary_logo',
          type: 'file',
          label: 'Primary logo',
          hint: 'Full lockup — SVG · PNG · PDF · AI',
          accept: 'image/*,.svg,.pdf,.ai',
          multiple: true,
          halfWidth: true,
        },
        {
          id: 'logo_mark',
          type: 'file',
          label: 'Logo mark / icon',
          hint: 'The symbol alone — SVG · PNG',
          accept: 'image/*,.svg',
          multiple: true,
          halfWidth: true,
        },
        {
          id: 'favicon',
          type: 'file',
          label: 'Favicon',
          hint: 'Browser-tab icon, optional — PNG · ICO · SVG',
          accept: 'image/*,.ico,.svg',
          multiple: true,
          halfWidth: true,
        },
        {
          id: 'brand_guidelines_file',
          type: 'file',
          label: 'Brand guidelines file',
          hint: 'If you have one — PDF · any',
          multiple: true,
          halfWidth: true,
        },
      ],
    },

    {
      id: 'colors',
      num: '03',
      title: 'Brand colours',
      description: "We've pre-loaded your NutriPath palette — adjust any hex, or tell us about more in the notes below.",
      fields: [
        {
          id: 'color_primary_green',
          type: 'text',
          label: 'Primary green',
          hint: 'Headings, primary buttons, key accents',
          defaultValue: '#3A760D',
          halfWidth: true,
        },
        {
          id: 'color_bright_green',
          type: 'text',
          label: 'Bright green',
          hint: 'Highlights, hover, icons (large text only)',
          defaultValue: '#54B51B',
          halfWidth: true,
        },
        {
          id: 'color_charcoal',
          type: 'text',
          label: 'Charcoal',
          hint: 'Body text, dark sections',
          defaultValue: '#343433',
          halfWidth: true,
        },
        {
          id: 'color_mid_grey',
          type: 'text',
          label: 'Mid grey',
          hint: 'Secondary text, captions',
          defaultValue: '#767676',
          halfWidth: true,
        },
        {
          id: 'additional_colors',
          type: 'textarea',
          label: 'Additional brand colours',
          hint: 'Hex codes and what each is for, if you use more than the four above',
          placeholder: 'e.g., #FFFFFF — backgrounds, #F4F8EF — section tint',
          rows: 2,
        },
      ],
    },

    {
      id: 'theme',
      num: '04',
      title: 'Look & feel',
      description: 'Pick the direction that feels most "NutriPath." This sets the overall mood — we\'ll refine it together.',
      fields: [
        {
          id: 'theme',
          type: 'radio',
          label: 'Overall direction',
          layout: 'grid',
          options: [
            { value: 'clean-clinical', label: 'Clean & Clinical', description: 'Crisp, white-space-led, trustworthy. Reads as a serious, evidence-based platform. Lots of breathing room.' },
            { value: 'warm-human', label: 'Warm & Human', description: 'Softer tones, friendly photography, rounded shapes. Feels like a supportive mentor — reassuring for anxious learners.' },
            { value: 'bold-confident', label: 'Bold & Confident', description: 'Big type, high contrast, strong statements. Stands out and signals authority — for a brand that wants to lead the niche.' },
            { value: 'premium-editorial', label: 'Premium & Editorial', description: 'Serif headlines, refined spacing, magazine-like. Feels considered and high-end — premium positioning.' },
          ],
        },
        {
          id: 'inspiration_links',
          type: 'textarea',
          label: 'Sites or brands you love',
          hint: "Paste 2–5 links or names — yours or others'",
          placeholder: 'e.g., inabenkova.com (clean), acely.com (conversion), a brand whose feel you admire…',
          rows: 3,
        },
      ],
    },

    {
      id: 'typography',
      num: '05',
      title: 'Typography',
      description: 'The font personality. Pick a direction, or upload your brand fonts if you already have licensed ones.',
      fields: [
        {
          id: 'typography',
          type: 'radio',
          label: 'Font direction',
          layout: 'list',
          options: [
            { value: 'modern-sans', label: 'Modern Sans', description: 'Clean, neutral, highly legible. Safe, professional, great for accessibility.' },
            { value: 'serif-headlines', label: 'Serif Headlines', description: 'Elegant serif titles with a sans body. Adds warmth and a premium, editorial feel.' },
            { value: 'friendly-rounded', label: 'Friendly & Rounded', description: 'Approachable, soft letterforms. Feels human and welcoming — good for an anxious audience.' },
            { value: 'own-fonts', label: 'I have brand fonts', description: 'Use my own licensed typefaces — I\'ll upload them or name them below.' },
          ],
        },
        {
          id: 'font_names',
          type: 'text',
          label: 'Font names',
          hint: 'If you have specific ones',
          placeholder: 'e.g., Headings: Fraunces · Body: Inter',
          halfWidth: true,
        },
        {
          id: 'font_files',
          type: 'file',
          label: 'Upload font files',
          hint: 'If licensed — WOFF · WOFF2 · OTF · TTF',
          accept: '.woff,.woff2,.otf,.ttf',
          multiple: true,
          halfWidth: true,
        },
      ],
    },

    {
      id: 'voice',
      num: '06',
      title: 'Voice & tone',
      description: 'How NutriPath should sound in writing — on the homepage, in emails, everywhere.',
      fields: [
        {
          id: 'voice_traits',
          type: 'checkboxgroup',
          label: 'Pick the traits that fit (up to 5)',
          layout: 'list',
          maxSelect: 5,
          options: [
            { value: 'warm', label: 'Warm' },
            { value: 'reassuring', label: 'Reassuring' },
            { value: 'expert', label: 'Expert' },
            { value: 'authoritative', label: 'Authoritative' },
            { value: 'friendly', label: 'Friendly' },
            { value: 'empowering', label: 'Empowering' },
            { value: 'calm', label: 'Calm' },
            { value: 'professional', label: 'Professional' },
            { value: 'conversational', label: 'Conversational' },
            { value: 'premium', label: 'Premium' },
            { value: 'down-to-earth', label: 'Down-to-earth' },
            { value: 'motivating', label: 'Motivating' },
          ],
        },
        {
          id: 'tone_formal_casual',
          type: 'slider',
          label: 'Formal ↔ Casual',
          defaultValue: '55',
          options: [
            { value: '0', label: 'Formal' },
            { value: '100', label: 'Casual' },
          ],
        },
        {
          id: 'tone_serious_playful',
          type: 'slider',
          label: 'Serious ↔ Playful',
          defaultValue: '35',
          options: [
            { value: '0', label: 'Serious' },
            { value: '100', label: 'Playful' },
          ],
        },
        {
          id: 'tone_reserved_bold',
          type: 'slider',
          label: 'Reserved ↔ Bold',
          defaultValue: '50',
          options: [
            { value: '0', label: 'Reserved' },
            { value: '100', label: 'Bold' },
          ],
        },
        {
          id: 'words_to_use',
          type: 'textarea',
          label: 'Words / phrases you love',
          hint: 'Always-use language',
          placeholder: "e.g., 'internationally educated dietitians', 'pass with confidence', 'built by RDs'",
          rows: 3,
          halfWidth: true,
        },
        {
          id: 'words_to_avoid',
          type: 'textarea',
          label: 'Words to avoid',
          hint: 'Never-use language',
          placeholder: "e.g., 'cheap', 'guaranteed pass', overly clinical jargon, hype",
          rows: 3,
          halfWidth: true,
        },
      ],
    },

    {
      id: 'story',
      num: '07',
      title: 'Your story & content',
      description: 'The words for your About page and key sections. Rough notes are fine — we\'ll polish into final copy.',
      fields: [
        {
          id: 'mission',
          type: 'textarea',
          label: 'Mission — why does NutriPath exist?',
          placeholder: 'What change are you trying to make for internationally educated dietitians?',
          rows: 3,
        },
        {
          id: 'founder_story',
          type: 'textarea',
          label: "Founder story",
          hint: "Berin's journey, in your words",
          placeholder: 'How and why you started NutriPath — the personal reason behind it.',
          rows: 3,
        },
        {
          id: 'differentiators',
          type: 'textarea',
          label: 'What makes NutriPath different?',
          placeholder: 'Built by RDs, accessibility-first, CDRE+KCAT specialists, community…',
          rows: 3,
        },
        {
          id: 'team_bios',
          type: 'textarea',
          label: 'Team / RD bios',
          hint: 'Names, credentials, short bio',
          placeholder: 'Berin Arikan, RD — founder…\nSylvia Sun, RD — content…\nKristine Brigino, RD — content…',
          rows: 4,
          halfWidth: true,
        },
        {
          id: 'key_stats',
          type: 'textarea',
          label: 'Key facts / stats to highlight',
          placeholder: 'e.g., 25 founding seats, Nov 2026 pilot, AODA accessible…',
          rows: 4,
          halfWidth: true,
        },
      ],
    },

    {
      id: 'images',
      num: '08',
      title: 'About & team imagery',
      description: 'Photos that make the site feel real and human — founder, team, and any brand photography.',
      fields: [
        {
          id: 'founder_headshot',
          type: 'file',
          label: 'Founder headshot',
          hint: 'JPG · PNG · high-res',
          accept: 'image/*',
          multiple: true,
          halfWidth: true,
        },
        {
          id: 'team_photos',
          type: 'file',
          label: 'Team photos',
          hint: 'Multiple OK',
          accept: 'image/*',
          multiple: true,
          halfWidth: true,
        },
        {
          id: 'photography_direction',
          type: 'textarea',
          label: "Photography direction",
          hint: "If you don't have photos yet",
          placeholder: 'e.g., warm, natural light, real dietitians (not stock); diverse, Canadian; calm study settings.',
          rows: 3,
        },
      ],
    },

    {
      id: 'proof',
      num: '09',
      title: 'Social proof',
      description: 'Testimonials, outcomes, and partner logos build trust fast. Add whatever you have.',
      fields: [
        {
          id: 'testimonials',
          type: 'textarea',
          label: 'Testimonials / reviews',
          hint: 'Quote — name — location/role',
          placeholder: '"Passed the CDRE on my second try…" — Aanya R., Ontario\n"Finally prep made for the Canadian exam." — María L., BC',
          rows: 4,
        },
        {
          id: 'outcomes',
          type: 'textarea',
          label: 'Outcomes / numbers to feature',
          placeholder: 'Pass rates, # of students helped, ratings… (only if real)',
          rows: 3,
          halfWidth: true,
        },
        {
          id: 'partner_logos',
          type: 'file',
          label: 'Partner / press logos',
          hint: 'SVG · PNG',
          accept: 'image/*,.svg',
          multiple: true,
          halfWidth: true,
        },
      ],
    },

    {
      id: 'media',
      num: '10',
      title: 'Media library',
      description: "Any other images, video, icons, illustrations, or documents you'd like used on the site.",
      fields: [
        {
          id: 'media_library',
          type: 'file',
          label: 'Drop any media here',
          hint: 'Images · video · PDFs · zip — multiple files OK',
          multiple: true,
        },
        {
          id: 'media_notes',
          type: 'textarea',
          label: 'Notes about these files',
          hint: 'Where each should go, what to skip',
          placeholder: "e.g., 'use the hero video on the homepage', 'the PDF is the KCAT syllabus for the resources page'.",
          rows: 3,
        },
      ],
    },

    {
      id: 'accounts',
      num: '11',
      title: 'Accounts & links',
      description: "So we can connect the website to the right tools. Don't paste passwords — we'll request access securely later.",
      fields: [
        {
          id: 'social_links',
          type: 'textarea',
          label: 'Social media links',
          placeholder: 'Instagram, LinkedIn, TikTok, YouTube…',
          rows: 3,
        },
        {
          id: 'existing_site',
          type: 'text',
          label: 'Existing site / pages (if any)',
          placeholder: "Current URL or 'none yet'",
          halfWidth: true,
        },
        {
          id: 'email_tool',
          type: 'text',
          label: 'Email tool',
          placeholder: 'Kit (ConvertKit)',
          halfWidth: true,
        },
        {
          id: 'payments',
          type: 'text',
          label: 'Payments',
          placeholder: 'Helcim (primary) · Stripe (Apple/Google Pay)',
          halfWidth: true,
        },
        {
          id: 'booking_tool',
          type: 'text',
          label: 'Booking tool for consults',
          placeholder: "Calendly / Cal.com — or 'need a recommendation'",
          halfWidth: true,
        },
        {
          id: 'analytics',
          type: 'text',
          label: 'Analytics',
          placeholder: "GA4 — or 'set it up for me'",
        },
      ],
    },

    {
      id: 'notes',
      num: '12',
      title: 'Anything else',
      description: "Things we didn't ask but you want us to know — must-haves, no-gos, deadlines, worries.",
      fields: [
        {
          id: 'final_notes',
          type: 'textarea',
          label: 'Notes for the Maxxlab team',
          placeholder: 'Anything at all — the KCAT page is most urgent, a hard launch date, a competitor look you want to avoid, etc.',
          rows: 6,
        },
      ],
    },
  ],
};

export default nutriPathBrandContent;
